import {
  Shirt,
  Crown,
  Baby,
  Users,
  Gift,
  Sparkles,
  Dumbbell,
  Heart,
  Church,
  Home,
  MoreHorizontal,
  ShirtIcon,
  Footprints,
  Watch,
  Glasses,
  Briefcase,
  Gem,
  ShoppingBag,
  SaladIcon as Dress,
  FootprintsIcon as Heels,
  Gamepad2,
  Wrench,
  Sofa,
  Utensils,
  Lightbulb,
  Bed,
} from "lucide-react";

export const categories = [
  {
    id: 1,
    name: "Men's Fashion",
    icon: Shirt,
    subcategories: [
      { name: "T-Shirts", icon: ShirtIcon },
      { name: "Shirts", icon: Shirt },
      { name: "Pants & Jeans", icon: Shirt },
      { name: "Shoes", icon: Footprints },
      { name: "Watches", icon: Watch },
      { name: "Accessories", icon: Glasses },
      { name: "Bags", icon: Briefcase },
      { name: "Underwear", icon: Heart },
    ],
  },
  {
    id: 2,
    name: "Women's Fashion",
    icon: Crown,
    subcategories: [
      { name: "Dresses", icon: Dress },
      { name: "Tops & Blouses", icon: ShirtIcon },
      { name: "Pants & Skirts", icon: Shirt },
      { name: "Shoes & Heels", icon: Heels },
      { name: "Handbags", icon: ShoppingBag },
      { name: "Jewelry", icon: Gem },
      { name: "Accessories", icon: Glasses },
      { name: "Lingerie", icon: Heart },
    ],
  },
  {
    id: 3,
    name: "Kids Fashion",
    icon: Baby,
    subcategories: [
      { name: "Boys Clothing", icon: Shirt },
      { name: "Girls Clothing", icon: Crown },
      { name: "Baby Clothes", icon: Baby },
      { name: "Kids Shoes", icon: Footprints },
      { name: "School Uniforms", icon: Briefcase },
      { name: "Toys", icon: Gamepad2 },
    ],
  },
  {
    id: 4,
    name: "Family",
    icon: Users,
    subcategories: [
      { name: "Family Sets", icon: Users },
      { name: "Matching Outfits", icon: Shirt },
      { name: "Traditional Wear", icon: Gift },
      { name: "Casual Wear", icon: ShirtIcon },
    ],
  },
  {
    id: 5,
    name: "Eid Collections",
    icon: Gift,
    subcategories: [
      { name: "Men's Eid Wear", icon: Shirt },
      { name: "Women's Eid Wear", icon: Crown },
      { name: "Kids Eid Wear", icon: Baby },
      { name: "Traditional Kurta", icon: Gift },
      { name: "Eid Accessories", icon: Gem },
    ],
  },
  {
    id: 6,
    name: "Festivals Collections",
    icon: Sparkles,
    subcategories: [
      { name: "Puja Collection", icon: Sparkles },
      { name: "Wedding Collection", icon: Church },
      { name: "Party Wear", icon: Crown },
      { name: "Traditional Sarees", icon: Dress },
    ],
  },
  {
    id: 7,
    name: "Sports Wear",
    icon: Dumbbell,
    subcategories: [
      { name: "Gym Wear", icon: Dumbbell },
      { name: "Running Shoes", icon: Footprints },
      { name: "Sports T-Shirts", icon: ShirtIcon },
      { name: "Athletic Shorts", icon: Shirt },
      { name: "Sports Accessories", icon: Watch },
    ],
  },
  {
    id: 8,
    name: "Lingerie",
    icon: Heart,
    subcategories: [
      { name: "Bras", icon: Heart },
      { name: "Panties", icon: Heart },
      { name: "Nightwear", icon: Shirt },
      { name: "Shapewear", icon: Crown },
    ],
  },
  {
    id: 9,
    name: "Wedding",
    icon: Church,
    subcategories: [
      { name: "Bridal Wear", icon: Crown },
      { name: "Groom Wear", icon: Shirt },
      { name: "Wedding Accessories", icon: Gem },
      { name: "Wedding Shoes", icon: Heels },
    ],
  },
  {
    id: 10,
    name: "Home Textile",
    icon: Home,
    subcategories: [
      { name: "Bed Sheets", icon: Bed },
      { name: "Curtains", icon: Home },
      { name: "Towels", icon: Home },
      { name: "Cushions", icon: Sofa },
      { name: "Table Cloth", icon: Utensils },
    ],
  },
  {
    id: 11,
    name: "Others",
    icon: MoreHorizontal,
    subcategories: [
      { name: "Electronics", icon: Lightbulb },
      { name: "Books", icon: Briefcase },
      { name: "Health & Beauty", icon: Heart },
      { name: "Tools", icon: Wrench },
    ],
  },
];
